### ISSUE TITLE
Video generated is corrupted  under /allure-raw folder

### ISSUE THREAD

**Issue by namanbada0606** [presidenten/wdio-video-reporter#7] opened 2019-05-12 19:17 UTC
**Describe the bug**
I'm using this library with `version ^1.3.2`, Tests runs fine, generates the videos however recently observed this wired issue when viewing the report with Allure for videos the mime is incorrect. 

 My reporters' options - 

    reporters: [
        'spec',
        [video, {
            saveAllVideos: true,       // If true, also saves videos for successful test cases
            videoSlowdownMultiplier: 10, // Higher to get slower videos, lower for faster videos [Value 1-100]
            videoRenderTimeout: 5,      // Max seconds to wait for a video to finish rendering
        }],
        ['allure', {
            outputDir: './_results_/allure-raw',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: true,
        }],
    ],

![image](https://user-images.githubusercontent.com/49596631/57586701-eb2d5f80-74b6-11e9-9fea-5bff7612ce89.png)

Videos generated under _results_ are fine, it plays well,  however, the one under allure-raw with file extension .mp4 does not play.  

Spend the whole day finding the issue, did not get a breakthrough. 

Reinstalled all npm modules of  `@ffmpeg-installer/ffmpeg` no luck 

**Expected behavior**
Expect both videos to work the one from _results_ and under allure raw

Environment (please complete the following information):

wdio-video-reporter version: 1.3.2
WebdriverIO version: 5.3.8
Mode: command line
Node.js version: 8.11.1
NPM version: 5.6.0
Browser name and version: FF latest
Platform name and version: Mac X10
Desktop (please complete the following information):

OS: Mac OS High Siera
Browser: FF / Chrome latest
Version: 74

Appreciate any help or a workaround for video's to work with allure reports 

Thanks

**Comment by presidenten** [comment] 2019-05-12 22:08
I tried installing node 8.11.1 and I am running my tests in Firefox, but I cant seem to reproduce the issue even though Im running osx as well.

Would you mind creating an example project for me to download where this problem happens so I can try it?

**Comment by presidenten** [comment] 2019-05-13 12:26
There might be something happening in the tests which blocks the finalization of syncing the videos into the allure_raw dir. Thats why it would be of great help to see an example where this is happening.

If you check the videos in allure_raw, they are probably still placeholders with only a string path inside of them.

**Comment by namanbada0606** [comment] 2019-05-13 13:45
Hello @presidenten  

Thank you for your help.

I have provided an incorrect node and npm version above, my bad 

Here are the correct ones - 

⇒  node -v
v10.15.3

⇒  npm -v
6.4.1

Interestingly the video  under `_results_` plays fine no issue, however the ones under `/allure-raw` is corrupted. 

I will downgrade Node version to 8.11 and let you know, The upgrade was done as NPM is now recommending v10 

Thanks again

**Comment by presidenten** [comment] 2019-05-13 14:23
I dont think node version is the problem.
We are using node v10 as well. I switched to v8 to try to verify your issue.

If you could make a small example project for me where the issue is present, it would be easier for me to try to help you

**Comment by namanbada0606** [comment] 2019-05-14 02:34
Give me some time, will create a sample repo

**Comment by presidenten** [comment] 2019-05-14 07:31
I managed to recreate the issue on my work computer. So no need to make repo.
Ill try to fix it during the day.

**Comment by presidenten** [comment] 2019-05-14 09:32
Issue is fixed in ^1.3.4

**Closed by presidenten** 2019-05-14 09:32 UTC
Labels: bug

**Comment by namanbada0606** [comment] 2019-05-14 15:02
Thank you @presidenten   The fix worked like a breeze.

Totally Brilliant, Thank you so much 

Cheers,
