### ISSUE TITLE
Video is not generated onWindows10 and Windows Server.

### ISSUE THREAD

**Issue by danielsaf** [presidenten/wdio-video-reporter#19] opened 2019-07-18 12:50 UTC
**Describe the bug**
On macOs video is generated but on Windows 10 and Windows Server is not.

**Log**
Using reporter config:[
  "spec",
  [
    null,
    {
      "saveAllVideos": true,
      "videoSlowdownMultiplier": 5,
      "videoRenderTimeout": 10
    }
  ],
  [
    "allure",
    {
      "outputDir": "reports/allure-results_310",
      "disableWebdriverStepsReporting": true,
      "disableWebdriverScreenshotsReporting": true
    }
  ],
  [
    "junit",
    {
      "outputDir": "reports/junit_310"
    }
  ]
]

Using config:{
  "debugMode": false,
  "logLevel": "info",
  "videoRenderTimeout": 10,
  "outputDir": "reports",
  "allureOutputDir": "C:\\Projects\\komplett.payments\\Tests\\Komplett.Payments.UI.Tests\\reports\\allure-results_310",
  "rawPath": "rawSeleniumVideoGrabs",
  "usingAllure": true,
  "saveAllVideos": true,
  "videoSlowdownMultiplier": 5,
  "excludedActions": [],
  "jsonWireActions": [
    "url",
    "forward",
    "back",
    "refresh",
    "execute",
    "size",
    "position",
    "maximize",
    "click",
    "submit",
    "value",
    "keys",
    "clear",
    "selected",
    "enabled",
    "displayed",
    "orientation",
    "alert_text",
    "accept_alert",
    "dismiss_alert",
    "moveto",
    "buttondown",
    "buttonup",
    "doubleclick",
    "down",
    "up",
    "move",
    "scroll",
    "doubleclick",
    "longclick",
    "flick",
    "location"
  ]
}

Max waiting time: 10s

--- Video C:\Projects\komplett.payments\Tests\Komplett.Payments.UI.Tests\reports\Update-B2B-recipient-shipping-address---Your-user-name-is-Auto-B2B-fsdfsdfsfsfsdfsf-and-your-pass-is-fsdfgsfgsgsgsg---Cancel-up--ile-page---C9468-should-click-on-Edit-recipient-button-and-cancel-update-shipping-address---CHROME--07-18-2019--14-05-09-882.mp4 ---
Waiting for video to exist: 0s
Waiting for video to exist: 1s
Waiting for video to exist: 2s
Waiting for video to exist: 3s
Waiting for video to exist: 4s
Waiting for video to exist: 5s
Waiting for video to exist: 6s
Waiting for video to exist: 7s
Waiting for video to exist: 8s
Waiting for video to exist: 9s
Waiting for video to exist: 10s

--- Video C:\Projects\komplett.payments\Tests\Komplett.Payments.UI.Tests\reports\Update-B2B-recipient-shipping-address---Your-user-name-is-dhagdfjhdsfjsfjjhsfsj-and-your-pass-is-adafafaf---Cancel-up--t-button-and-change-shipping-address-and-phone-number-and-not-update-data-on-profile-page---CHROME--07-18-2019--14-05-11-962.mp4 ---
Waiting for video to exist: 0s
Waiting for video to exist: 1s
Waiting for video to exist: 2s
Waiting for video to exist: 3s
Waiting for video to exist: 4s
Waiting for video to exist: 5s
Waiting for video to exist: 6s
Waiting for video to exist: 7s
Waiting for video to exist: 8s
Waiting for video to exist: 9s
Waiting for video to exist: 10s

--- Video C:\Projects\komplett.payments\Tests\Komplett.Payments.UI.Tests\reports\Update-B2B-recipient-shipping-address---Your-user-name-is-Auto-B2B-blalskalakjddd-no-and-your-pass-is-asdhjahdjad---Cancel-up--not-update-shipping-address-on-my-profile-page---C9470-Should-Click-pay-and-finish-button---CHROME--07-18-2019--14-05-25-013.mp4 ---
Waiting for video to exist: 0s
Waiting for video to exist: 1s
Waiting for video to exist: 2s
Waiting for video to exist: 3s
Waiting for video to exist: 4s
Waiting for video to exist: 5s
Waiting for video to exist: 6s
Waiting for video to exist: 7s
Waiting for video to exist: 8s
Waiting for video to exist: 9s
Waiting for video to exist: 10s

--- Video C:\Projects\komplett.payments\Tests\Komplett.Payments.UI.Tests\reports\Update-B2B-recipient-shipping-address---Your-user-name-is-Auto-B2B-fgshgfshfhsgfhs-and-your-pass-is-blalala---Cancel-up--profile-page---C9471-Shipping-address-and-phone-number-should-not-changed-on-profile-page---CHROME--07-18-2019--14-05-36-853.mp4 ---
Waiting for video to exist: 0s
Waiting for video to exist: 1s
Waiting for video to exist: 2s
Waiting for video to exist: 3s
Waiting for video to exist: 4s
Waiting for video to exist: 5s
Waiting for video to exist: 6s
Waiting for video to exist: 7s
Waiting for video to exist: 8s
Waiting for video to exist: 9s
Waiting for video to exist: 10s

Generated:[]

Done!

**To Reproduce**

**Expected behavior**
Video should generated

**Environment (please complete the following information):**
reporters: ['spec',
        [video, {
            saveAllVideos: true,       // If true, also saves videos for successful test cases
            videoSlowdownMultiplier: 5, // Higher to get slower videos, lower for faster videos [Value 1-100]
            videoRenderTimeout: 10,      // Max seconds to wait for a video to finish rendering
        }],
        ['allure', {
            outputDir: `reports/allure-results_${process.env.npm_config_storeId}`,
            disableWebdriverStepsReporting: false,
            disableWebdriverScreenshotsReporting: false,
        }],
        ['junit', {
            outputDir: `reports/junit_${process.env.npm_config_storeId}`,
            outputFileFormat: function(opts) { // optional
                return `results-${opts.cid}.${opts.capabilities}.xml`
            }
        }]
    ],

mochaOpts: {
        ui: 'bdd',
        timeout: 9999999,
        compilers: ["js:babel-core/register", 'js:babel-register'],
        require: "mocha-clean",
    },

    "@wdio/allure-reporter": "5.11.0",
    "@wdio/cli": "5.11.6",
    "@wdio/concise-reporter": "5.11.0",
    "@wdio/devtools-service": "5.11.0",
    "@wdio/dot-reporter": "5.11.0",
    "@wdio/firefox-profile-service": "5.11.0",
    "@wdio/junit-reporter": "5.11.0",
    "@wdio/local-runner": "5.11.6",
    "@wdio/mocha-framework": "5.11.0",
    "@wdio/selenium-standalone-service": "5.11.2",
    "@wdio/spec-reporter": "5.11.6",
    "@wdio/sumologic-reporter": "5.11.0",
    "@wdio/sync": "5.11.0",
"wdio-chromedriver-service": "5.0.2",
    "wdio-errorshot-reporter": "0.2.1",
    "wdio-iedriver-service": "0.1.0",
    "wdio-json-reporter": "1.3.0",
    "wdio-mochawesome-reporter": "3.1.0",
    "wdio-screenshots-cleanup-service": "0.0.7",
    "wdio-testrail-reporter": "1.1.5",
    "wdio-timeline-reporter": "5.0.10",
    "wdio-video-reporter": "1.4.4"

**Desktop (please complete the following information):**
 - Windows 10 and  Windows Server
 - Chrome 75.0.3775
- Node 10.16.0
- npm 6.10.0

**Comment by presidenten** [comment] 2019-08-27 16:42
I will try to run some tests with the template project on a win10 machine when I get to work tomorrow. But Im wondering if its the library by it self or when used with mocha that is the problem.

If I cannot reproduce, Ill be back to ask you to fork https://github.com/presidenten/wdio-template and set up a simple scenario where it happens.

But let me check first.

**Comment by presidenten** [comment] 2019-08-28 09:07
I cant verify this on Windows 10. I have a freshly installed win10 pro running node 10.16.3 and selenium in a docker (since I have no clue how to get selenium standalone to work).

Maybe its an issue with the environment variables that you are using in the config?

Anyways, please fork https://github.com/presidenten/wdio-template and set up a simple scenario where the issue can be reproduced.

**Comment by presidenten** [comment] 2019-12-18 17:00
Closing this because no more input. Reach out again if issue arises again

**Closed by presidenten** 2019-12-18 17:00 UTC
Labels: more info needed
